[package]
name = "enigma_principal_app"
version = "0.1.3"
authors = ["Enigma <support@enigma.co>"]
build = "build.rs"

[dependencies]
enigma-tools-u = {path = "../../enigma-tools-u"}
enigma-crypto = { path = "../../enigma-crypto" }

base64 = "0.10.0"
libc = "0.2.41"
etcommon-rlp = "0.2"
failure = "0.1.3"
failure_derive = "0.1.3"
rustc-hex = "1.0.0"
tokio-core = "0.1.17"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2.10"
url = "1.7.1"
tiny-keccak = "1.4.2"
colour = "0.2.1"
dirs = "1.0"
web3 = { git = "https://github.com/tomusdrw/rust-web3.git" } #TODO: Change after a new version is released.


sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6" }