[package]
name = "enigma-runtime-t"
version = "0.1.0"
authors = ["Elichai Turkel <elichai@enigma.co>"]

[dependencies]
enigma-types = { path = "../enigma-types", default-features = false, features = ["sgx"] }
enigma-crypto = { path = "../enigma-crypto", default-features = false, features = ["sgx", "asymmetric"] }
enigma-tools-t = { path = "../enigma-tools-t" }

rmp-serde = { git = "https://github.com/enigmampc/msgpack-rust.git", rev =  "sgx-v1.0.6" }
json-patch = { git = "https://github.com/enigmampc/json-patch.git", rev = "sgx-0.2.2-v1.0.6" }


wasmi = { git = "https://github.com/enigmampc/wasmi", rev = "sgx-1.0.6" }


serde_json = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6" }
serde = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6", default-features = false, features=["serde_derive"] }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6" }
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6" }
sgx_trts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.6" }